### ISSUE TITLE
Layer Control Labels

### ISSUE THREAD

**Issue by mbasa-georepublic** [gtt-project/redmine_gtt#163]
Labels in the `Layer Control` are truncated when creating a new Issue or editing an existing issue. 

![image](https://user-images.githubusercontent.com/68265868/180971389-d99c5e01-5004-43cd-9aed-ddc3894b5468.png)

**Comment by sanak** [comment]
@mbasa-georepublic Thanks for reporting this issue !

I will take a look about this issue at tomorrow.

**Comment by sanak** [comment]
Sorry for late reply, but I could reproduce this issue, so I will try to fix this.

**Comment by sanak** [comment]
The cause was new/edit issue's `LayerSwitcher` is affected by Redmine's CSS style `.tabular label`, so disabling the style for `.ol-layerswitcher` will become necessary.
![layer-switcher-invalid-label-when-new-and-edit-issue](https://user-images.githubusercontent.com/629923/188251528-57a5bf28-5793-49d7-a409-314b75bcb572.png)
