### ISSUE TITLE
Problem / compatibility with additional_tags addon

### ISSUE THREAD

**Issue by whotopia** [gtt-project/redmine_gtt#252]
Hi,
When I install the addition_tags addon along with redmine_gtt, I run into an issue when visiting the http://localhost:3000/settings url it generates error.  In the logs:
```
SystemStackError (stack level too deep):
docker-gtt-ent-redmine-1  |   
docker-gtt-ent-redmine-1  | plugins/redmine_gtt/lib/redmine_gtt/patches/issue_query_patch.rb:39:in `available_columns'
docker-gtt-ent-redmine-1  | plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:63:in `available_columns_with_tags'
docker-gtt-ent-redmine-1  | plugins/redmine_gtt/lib/redmine_gtt/patches/issue_query_patch.rb:39:in `available_columns'
docker-gtt-ent-redmine-1  | plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:63:in `available_columns_with_tags'
docker-gtt-ent-redmine-1  | plugins/redmine_gtt/lib/redmine_gtt/patches/issue_query_patch.rb:39:in `available_columns'
docker-gtt-ent-redmine-1  | plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:63:in `available_columns_with_tags'
docker-gtt-ent-redmine-1  | plugins/redmine_gtt/lib/redmine_gtt/patches/issue_query_patch.rb:39:in `available_columns'
docker-gtt-ent-redmine-1  | plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:63:in `available_columns_with_tags'
docker-gtt-ent-redmine-1  | plugins/redmine_gtt/lib/redmine_gtt/patches/issue_query_patch.rb:39:in `available_columns'
docker-gtt-ent-redmine-1  | plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:63:in `available_columns_with_tags'
docker-gtt-ent-redmine-1  | plugins/redmine_gtt/lib/redmine_gtt/patches/issue_query_patch.rb:39:in `available_columns'
```

Many many lines of the above error are generated.

**Comment by dkastl** [comment]
Could it be a similar issue as in here?
https://github.com/gtt-project/redmine_gtt/issues/151

Could you provide a link to the plugin? If I remember right then this plugin is from the same developer.

**Comment by dkastl** [comment]
Also see https://stackoverflow.com/a/59043779 why redmine_gtt uses `prepend`.

**Comment by whotopia** [comment]
> Could it be a similar issue as in here? #151
> 
> Could you provide a link to the plugin? If I remember right then this plugin is from the same developer.

Need to install 
https://github.com/alphanodes/additionals <-- This works fine and is a dependency of the one with the problem
https://github.com/AlphaNodes/additional_tags.  <-- the one with the issue

**Comment by dkastl** [comment]
The problem seems to be discussed at various places, here some links:
- https://www.redmine.org/issues/34743
- https://github.com/alphanodes/additional_tags/issues/9#issuecomment-835752314

**Comment by dkastl** [comment]
I've been looking a bit into possibilities to find a solution for this issue. 
But when looking at the `additionals` plugin I found the project map block missing from the project overview page.

Reading through the code it became obvious that the `additionals` plugin "replaces" the project overview page with its own implementation and therefor "drops" the project map. "Customization" in this way seems to be a common pattern through the plugin, which makes it practically impossible for the GTT plugin to work as intended without making the `additionals` plugin a known dependency. 

I don't think this is the correct way, but if someone has a feasible solution to ensure compliance, I'm open to discuss.

For now it seems to me that neither `additionals` nor `additional_tags` plugin are compliant with `redmine_gtt`. The latter due to the inability for some other plugins to migrate to `prepend`, the former because it overrides relevant parts of Redmine.
