### ISSUE TITLE
Inverse polygon on project overview page

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt#59]
Similar as with issues list map the project overview map could show the project area with an inverse map.

Now

![Screenshot from 2021-03-26 10-55-08](https://user-images.githubusercontent.com/227762/112566241-f1feba80-8e21-11eb-8c99-86cd7db5d5bd.png)

Change to

![Screenshot from 2021-03-26 10-57-19](https://user-images.githubusercontent.com/227762/112566322-0fcc1f80-8e22-11eb-9acb-057034c5599b.png)

**Comment by sanak** [comment]
Well, I missed this issue...  
I will check this issue on develop branch.

**Comment by sanak** [comment]
@dkastl I confirmed this issue on `master` branch, so I guess that this issue started to happen from my past ol-ext update (https://github.com/gtt-project/redmine_gtt/commit/727f94f375e81850dc55ec4f56027664f5ebfa74)... 🙇‍♂️ 💦

**Comment by sanak** [comment]
@dkastl  
Well, this may be design related topic, but in case of project overview/settings, showing only polygon (without inverse red polygon) may be better, because in issues list, overlaying issue's geometry and showing project inverse polygon is better to avoid mixed overlay color, but in case of project overview/setting, checking project area is more important.

Also, I noticed that polygon fill color is always same value `rgba(255, 136, 0, 0.2)` value, but is it better to use `stroke color with alpha 0.2` as fill color for example ?  
![geometry_styles](https://user-images.githubusercontent.com/629923/118594594-ad214f80-b7e4-11eb-925a-2a0b1fd9b22d.png)  
![plugin_status_color](https://user-images.githubusercontent.com/629923/118594616-b3173080-b7e4-11eb-8cea-eaf8ac3e89b0.png)

**Comment by dkastl** [comment]
It seems like the inverse polygon needs to be handled more conistently on multiple places.
In general inverse polygons are convenient, however multi-polygons could cause problems.

**Comment by sanak** [comment]
Okay, sure...  
I will think about this more carefully.  
Thanks for advice.
